version: '3.8'
services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: swaadgali
      POSTGRES_PASSWORD: password
      POSTGRES_DB: swaadgali
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgres://swaadgali:password@postgres:5432/swaadgali
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres-data:
